concurrent = 10
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ip-172-30-5-128"
  url = "https://gitlab.com"
  id = 41053008
  token = "***********"
  token_obtained_at = 2024-09-06T19:48:14Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker+machine"
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
    [runners.cache.s3]
      ServerAddress = ""
      BucketName = ""
      BucketLocation = "us-east-1"
      Insecure = false
   [runners.machine]
    IdleCount = 0
    IdleTime = 1800
    MaxBuilds = 20
    MachineDriver = "amazonec2"
    MachineName = "gitlab-docker-runner-%s"
    MachineOptions = [
      "amazonec2-access-key=************",
      "amazonec2-secret-key=***************",
      "amazonec2-region=us-east-1",
      "amazonec2-vpc-id=",
      "amazonec2-subnet-id=",
      "amazonec2-zone=b",
      "amazonec2-ami=",
      "amazonec2-instance-type=",
      "amazonec2-use-private-address=true",
      "amazonec2-tags=runner-manager-name,gitlab-aws-autoscaler,gitlab,true,gitlab-runner-autoscale,true",
      "amazonec2-security-group=gitlab-runner-sys",
      "engine-install-url='https://releases.rancher.com/install-docker/20.10.21.sh'",
   ]
   [[runners.machine.autoscaling]]
      Periods = ["* * 9-18 * * mon-fri *"]
      IdleCount = 1
      IdleTime = 3600
      Timezone = "UTC"
    [[runners.machine.autoscaling]]
      Periods = ["* * * * * sat,sun *"]
      IdleCount = 1
      IdleTime = 60
      Timezone = "UTC"
